/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Employee;
import model.Employee_list;

/**
 *
 * @author essni
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    
    Employee_list list;
    
    public CreatePanel(Employee_list list) {
        initComponents();
        this.list=list;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnGroup = new javax.swing.ButtonGroup();
        jTitle = new javax.swing.JLabel();
        jName = new javax.swing.JLabel();
        jEmpId = new javax.swing.JLabel();
        jAge = new javax.swing.JLabel();
        jGender = new javax.swing.JLabel();
        jDate = new javax.swing.JLabel();
        jLevel = new javax.swing.JLabel();
        jInfo = new javax.swing.JLabel();
        jPosTitle = new javax.swing.JLabel();
        jNum = new javax.swing.JLabel();
        jEmail = new javax.swing.JLabel();
        jTxtName = new javax.swing.JTextField();
        jTxtPosTitle = new javax.swing.JTextField();
        jTxtEmail = new javax.swing.JTextField();
        jTxtNum = new javax.swing.JTextField();
        jTxtAge = new javax.swing.JTextField();
        jTxtEmpId = new javax.swing.JTextField();
        jTxtDate = new javax.swing.JTextField();
        jTxtInfo = new javax.swing.JTextField();
        jTxtLevel = new javax.swing.JTextField();
        jBtnSave = new javax.swing.JButton();
        jRBMale = new javax.swing.JRadioButton();
        jRBFemale = new javax.swing.JRadioButton();
        jBtnClear = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(700, 600));

        jTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitle.setText("Create Employee");

        jName.setText("Name:");

        jEmpId.setText("Employee Id:");

        jAge.setText("Age:");

        jGender.setText("Gender:");

        jDate.setText("Start Date:");

        jLevel.setText("Level:");

        jInfo.setText("Team Info:");

        jPosTitle.setText("Position Title:");

        jNum.setText("Phone number:");

        jEmail.setText("email:");

        jTxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNameActionPerformed(evt);
            }
        });

        jTxtPosTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPosTitleActionPerformed(evt);
            }
        });

        jTxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmailActionPerformed(evt);
            }
        });

        jTxtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNumActionPerformed(evt);
            }
        });

        jTxtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAgeActionPerformed(evt);
            }
        });

        jTxtEmpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmpIdActionPerformed(evt);
            }
        });

        jTxtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDateActionPerformed(evt);
            }
        });

        jTxtInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtInfoActionPerformed(evt);
            }
        });

        jTxtLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtLevelActionPerformed(evt);
            }
        });

        jBtnSave.setText("Save");
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });

        jBtnGroup.add(jRBMale);
        jRBMale.setText("Male");
        jRBMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBMaleActionPerformed(evt);
            }
        });

        jBtnGroup.add(jRBFemale);
        jRBFemale.setText("Female");

        jBtnClear.setText("Clear");
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });

        jBtnGroup.add(jRadioButton1);
        jRadioButton1.setText("Prefer not to say");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jName)
                    .addComponent(jEmail)
                    .addComponent(jNum)
                    .addComponent(jPosTitle)
                    .addComponent(jInfo)
                    .addComponent(jLevel)
                    .addComponent(jDate)
                    .addComponent(jGender)
                    .addComponent(jEmpId)
                    .addComponent(jAge))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtPosTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRBMale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBFemale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnSave)))
                .addGap(51, 51, 51))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jAge, jDate, jEmail, jEmpId, jGender, jInfo, jLevel, jName, jNum, jPosTitle});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtnClear, jBtnSave});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jName)
                    .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmpId)
                    .addComponent(jTxtEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAge)
                    .addComponent(jTxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGender)
                    .addComponent(jBtnSave)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRBFemale)
                        .addComponent(jRBMale)
                        .addComponent(jRadioButton1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDate)
                            .addComponent(jTxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLevel)
                            .addComponent(jTxtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jBtnClear)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInfo)
                    .addComponent(jTxtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPosTitle)
                    .addComponent(jTxtPosTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNum)
                    .addComponent(jTxtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmail)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNameActionPerformed

    private void jTxtPosTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPosTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPosTitleActionPerformed

    private void jTxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmailActionPerformed

    private void jTxtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNumActionPerformed

    private void jTxtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAgeActionPerformed

    private void jTxtEmpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmpIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmpIdActionPerformed

    private void jTxtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDateActionPerformed

    private void jTxtInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtInfoActionPerformed

    private void jTxtLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtLevelActionPerformed

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        
        String name=jTxtName.getText();
        String eid=jTxtEmpId.getText();
        String age=jTxtAge.getText();
        //String gender=jTxtGender.getText();
        //String gender=jBtnGroup.getSelection().getActionCommand();
        String gender="Other";
        if(jRBMale.isSelected())
            gender="Male";
        else if(jRBFemale.isSelected())
            gender="Female";
        String date=jTxtDate.getText();
        String level=jTxtLevel.getText();
        String team_info=jTxtInfo.getText();
        String title=jTxtPosTitle.getText();
        String phone=jTxtNum.getText();
        String email=jTxtEmail.getText();
        //String photo;
        if(validation()){
            Employee e=list.addEmployee();
        
            e.setName(name);
            e.setEid(eid);
            e.setAge(age);
            e.setGender(gender);
            e.setDate(date);
            e.setLevel(level);
            e.setTeam_info(team_info);
            e.setTitle(title);
            e.setPhone(phone);
            e.setEmail(email);
        
            JOptionPane.showMessageDialog(this, "New Employee Added");

            jTxtName.setText("");
            jTxtEmpId.setText("");
            jTxtAge.setText("");
            //jTxtGender.setText("");
            jRBMale.setSelected(false);
            jRBFemale.setSelected(false);
            jTxtDate.setText("");
            jTxtLevel.setText("");
            jTxtInfo.setText("");
            jTxtPosTitle.setText("");
            jTxtNum.setText("");
            jTxtEmail.setText("");
            //String photo;
        }
        
        
    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jRBMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBMaleActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        jTxtName.setText("");
        jTxtEmpId.setText("");
        jTxtAge.setText("");
        //jTxtGender.setText("");
        jRBMale.setSelected(false);
        jRBFemale.setSelected(false);
        jTxtDate.setText("");
        jTxtLevel.setText("");
        jTxtInfo.setText("");
        jTxtPosTitle.setText("");
        jTxtNum.setText("");
        jTxtEmail.setText("");
    }//GEN-LAST:event_jBtnClearActionPerformed
    
    public boolean validation(){
        boolean res=true;
        if(String.valueOf(jTxtEmpId.getText()).equals("")){
            res=false;
            JOptionPane.showMessageDialog(this, "Please fill the Employee Id");
            jTxtEmpId.requestFocus();
        }else if(jTxtName.getText().equals("")){
            res=false;
            JOptionPane.showMessageDialog(this, "Please fill the Employee Name");
            jTxtName.requestFocus();
        }else if(String.valueOf(jTxtAge.getText()).equals("")){
            res=false;
            JOptionPane.showMessageDialog(this, "Please fill the Employee Age");
            jTxtAge.requestFocus();
        }else if(jRBMale.isSelected() && jRBFemale.isSelected()){
            res=false;
            JOptionPane.showMessageDialog(this, "Please fill the Employee Gender");
            //jTxtGender.requestFocus();
        }else if(jTxtDate.getText().equals("")){
            res=false;
            JOptionPane.showMessageDialog(this, "Please fill the Joining Date");
            jTxtDate.requestFocus();
        }else if(jTxtLevel.getText().equals("")){
            res=false;
            JOptionPane.showMessageDialog(this, "Please fill the Level");
            jTxtLevel.requestFocus();
        }else if(jTxtInfo.getText().equals("")){
            res=false;
            JOptionPane.showMessageDialog(this, "Please fill the Team Information of the Employee");
            jTxtInfo.requestFocus();
        }else if(jTxtPosTitle.getText().equals("")){
            res=false;
            JOptionPane.showMessageDialog(this, "Please fill the Position Title of the Employee");
            jTxtPosTitle.requestFocus();
        }else if(jTxtNum.getText().equals("")){
            res=false;
            JOptionPane.showMessageDialog(this, "Please fill the Phone Number of the Employee");
            jTxtNum.requestFocus();
        }else if(jTxtEmail.getText().equals("")){
            res=false;
            JOptionPane.showMessageDialog(this, "Please fill the eMail of the Employee");
            jTxtEmail.requestFocus();
        }
        return res;
    }
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAge;
    private javax.swing.JButton jBtnClear;
    private javax.swing.ButtonGroup jBtnGroup;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JLabel jDate;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jEmpId;
    private javax.swing.JLabel jGender;
    private javax.swing.JLabel jInfo;
    private javax.swing.JLabel jLevel;
    private javax.swing.JLabel jName;
    private javax.swing.JLabel jNum;
    private javax.swing.JLabel jPosTitle;
    private javax.swing.JRadioButton jRBFemale;
    private javax.swing.JRadioButton jRBMale;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel jTitle;
    private javax.swing.JTextField jTxtAge;
    private javax.swing.JTextField jTxtDate;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtEmpId;
    private javax.swing.JTextField jTxtInfo;
    private javax.swing.JTextField jTxtLevel;
    private javax.swing.JTextField jTxtName;
    private javax.swing.JTextField jTxtNum;
    private javax.swing.JTextField jTxtPosTitle;
    // End of variables declaration//GEN-END:variables
}
