/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Employee;
import model.Employee_list;

/**
 *
 * @author essni
 */
public class UpdatePanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdatePanel
     */
    
    Employee_list emplst;
    
    public UpdatePanel(Employee_list emplst) {
        initComponents();
        
        this.emplst=emplst;
        populateTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jUTable = new javax.swing.JTable();
        jName = new javax.swing.JLabel();
        jTxtName = new javax.swing.JTextField();
        jEmpId = new javax.swing.JLabel();
        jTxtEmpId = new javax.swing.JTextField();
        jAge = new javax.swing.JLabel();
        jTxtAge = new javax.swing.JTextField();
        jGender = new javax.swing.JLabel();
        jTxtGender = new javax.swing.JTextField();
        jDate = new javax.swing.JLabel();
        jTxtDate = new javax.swing.JTextField();
        jLevel = new javax.swing.JLabel();
        jTxtLevel = new javax.swing.JTextField();
        jInfo = new javax.swing.JLabel();
        jTxtInfo = new javax.swing.JTextField();
        jPosTitle = new javax.swing.JLabel();
        jTxtPosTitle = new javax.swing.JTextField();
        jNum = new javax.swing.JLabel();
        jTxtNum = new javax.swing.JTextField();
        jEmail = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jBtnFinalUpdate = new javax.swing.JButton();

        jUTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "EId", "Name", "Title", "Phone", "email"
            }
        ));
        jUTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jUTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jUTable);

        jName.setText("Name:");

        jTxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNameActionPerformed(evt);
            }
        });

        jEmpId.setText("Employee Id:");

        jTxtEmpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmpIdActionPerformed(evt);
            }
        });

        jAge.setText("Age:");

        jTxtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAgeActionPerformed(evt);
            }
        });

        jGender.setText("Gender:");

        jTxtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtGenderActionPerformed(evt);
            }
        });

        jDate.setText("Start Date:");

        jTxtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDateActionPerformed(evt);
            }
        });

        jLevel.setText("Level:");

        jTxtLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtLevelActionPerformed(evt);
            }
        });

        jInfo.setText("Team Info:");

        jTxtInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtInfoActionPerformed(evt);
            }
        });

        jPosTitle.setText("Position Title:");

        jTxtPosTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPosTitleActionPerformed(evt);
            }
        });

        jNum.setText("Phone number:");

        jTxtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNumActionPerformed(evt);
            }
        });

        jEmail.setText("email:");

        jTxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmailActionPerformed(evt);
            }
        });

        jBtnFinalUpdate.setText("Update");
        jBtnFinalUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFinalUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jName)
                                    .addComponent(jLevel)
                                    .addComponent(jDate)
                                    .addComponent(jGender)
                                    .addComponent(jEmpId)
                                    .addComponent(jAge))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jEmail)
                                    .addComponent(jNum)
                                    .addComponent(jPosTitle)
                                    .addComponent(jInfo))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtPosTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                        .addComponent(jBtnFinalUpdate)
                        .addGap(144, 144, 144))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jName)
                    .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmpId)
                    .addComponent(jTxtEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAge)
                    .addComponent(jTxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGender)
                    .addComponent(jTxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDate)
                    .addComponent(jTxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLevel)
                    .addComponent(jTxtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInfo)
                    .addComponent(jTxtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPosTitle)
                    .addComponent(jTxtPosTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNum)
                    .addComponent(jTxtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmail)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnFinalUpdate))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNameActionPerformed

    private void jTxtEmpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmpIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmpIdActionPerformed

    private void jTxtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAgeActionPerformed

    private void jTxtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtGenderActionPerformed

    private void jTxtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDateActionPerformed

    private void jTxtLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtLevelActionPerformed

    private void jTxtInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtInfoActionPerformed

    private void jTxtPosTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPosTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPosTitleActionPerformed

    private void jTxtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNumActionPerformed

    private void jTxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmailActionPerformed

    private void jBtnFinalUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFinalUpdateActionPerformed
        int select=jUTable.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel) jUTable.getModel();
        Employee emp=(Employee) model.getValueAt(select,0);
        
        emp.setName(jTxtName.getText());
        emp.setEid(jTxtEmpId.getText());
        emp.setAge(jTxtAge.getText());
        emp.setGender(jTxtGender.getText());
        emp.setDate(jTxtDate.getText());
        emp.setLevel(jTxtLevel.getText());
        emp.setTeam_info(jTxtInfo.getText());
        emp.setTitle(jTxtPosTitle.getText());
        emp.setPhone(jTxtNum.getText());
        emp.setEmail(jTxtEmail.getText());
        
        JOptionPane.showMessageDialog(this, "Employee details updated successfully");
    }//GEN-LAST:event_jBtnFinalUpdateActionPerformed

    private void jUTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUTableMouseClicked
        int select=jUTable.getSelectedRow();
        if(select<0){
            JOptionPane.showMessageDialog(this, "Please select an Employee");
            return;
        }
        
        DefaultTableModel model=(DefaultTableModel) jUTable.getModel();
        Employee emp=(Employee) model.getValueAt(select,0);
        
        jTxtName.setText(emp.getName());
        jTxtEmpId.setText(String.valueOf(emp.getEid()));
        jTxtAge.setText(String.valueOf(emp.getAge()));
        jTxtGender.setText(emp.getGender());
        jTxtDate.setText(emp.getDate());
        jTxtLevel.setText(emp.getLevel());
        jTxtInfo.setText(emp.getTeam_info());
        jTxtPosTitle.setText(emp.getTitle());
        jTxtNum.setText(String.valueOf(emp.getPhone()));
        jTxtEmail.setText(emp.getEmail());
    }//GEN-LAST:event_jUTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAge;
    private javax.swing.JButton jBtnFinalUpdate;
    private javax.swing.JLabel jDate;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jEmpId;
    private javax.swing.JLabel jGender;
    private javax.swing.JLabel jInfo;
    private javax.swing.JLabel jLevel;
    private javax.swing.JLabel jName;
    private javax.swing.JLabel jNum;
    private javax.swing.JLabel jPosTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtAge;
    private javax.swing.JTextField jTxtDate;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtEmpId;
    private javax.swing.JTextField jTxtGender;
    private javax.swing.JTextField jTxtInfo;
    private javax.swing.JTextField jTxtLevel;
    private javax.swing.JTextField jTxtName;
    private javax.swing.JTextField jTxtNum;
    private javax.swing.JTextField jTxtPosTitle;
    private javax.swing.JTable jUTable;
    // End of variables declaration//GEN-END:variables

    private void populateTabel() {
        DefaultTableModel model=(DefaultTableModel) jUTable.getModel();
        model.setRowCount(0);
        for(Employee e:emplst.getEmp_list()){
            Object[] col=new Object[5];
            col[0]=e;
            col[1]=e.getName();
            col[2]=e.getTitle();
            col[3]=e.getPhone();
            col[4]=e.getEmail();
            
            model.addRow(col);
        }
        
    }
}
